### ISSUE TITLE
Add a security warning

### ISSUE THREAD

**Issue by lc-at** [p4kl0nc4t/simaster.ics#5]
As _simaster.ics_ uses GET request, and credentials are passed openly, it is definitely a security issue.

It would be helpful if there is some warning in the `README.md` file telling about the security issue
and what could be done to prevent unwanted things.

**Comment by BlueBeret** [comment]
why don't you change the request method to POST?

**Comment by lc-at** [comment]
I don't think it's possible. Calendar providers including Google Calendar will not be happy (as far as I know, they only send GET requests).

We need a way to save the user credentials without actually saving them. Also, it has to be easy to use.

**Comment by BlueBeret** [comment]
Oh my bad, you are talking about the api, I was drunk when I made that comment 9 hours ago.

~~Does the user session expired when we use same  user-agent as their mobile device? If it doesn't, the app can save the  session, and token to encrypt the session (ex: https://simaster-ics.herokuapp.com/ics?period=2022&token=Y2lla2Vwbw). However, I don't think it's feasible nor easy to use since we also need user's user-agent.~~

Nevermind, it's same as saving user credential. You're right, I think it's impossible.

**Comment by lc-at** [comment]
> Does the user session expire..

I think it expires, so we can't rely on those tokens.

I've been thinking about encrypting their data with a public key from the server (but it's quite impractical). ~Also, it will also mean that we have their credentials because we have the private key, too.~

The safer way, I think, is to let the users refer to their credentials using a URL (e.g. secret paste with a specific format) which the server then sends a GET request to. But, again, it's more effort for the user. I will consider having that feature available in the future.

The safest way, for now, is to deploy our own instance.

**Comment by lc-at** [comment]
Closing this issue as password encryption feature is now available (#20).
